spring.application.name=demo

# conexion db
spring.datasource.url=jdbc:postgresql://localhost:5432/pr_java_003
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ddl auto
spring.jpa.hibernate.ddl-auto=update
